### ISSUE TITLE
I can't close the changelog window

### ISSUE THREAD

**Issue by lafleur63** [Repooc/ElvUI_ActionBarMasks#2]
I can't close the changelog window since the last update. I click the "close" button but that doesn't work.

**Comment by Repooc** [comment]
im actually almost done rewriting the changelog actually but there is a close button at the bottom after the timer runs out u will be able to click it

**Comment by Repooc** [comment]
also, a picture of what you see would be helpful as well

**Comment by Repooc** [comment]
try 1.11, report back with  pictures if u still have problems

**Comment by lafleur63** [comment]
It works now. Thank you.

**Comment by Repooc** [comment]
np
