### ISSUE TITLE
Doesn't work properly with 10.0.7

### ISSUE THREAD

**Issue by jdm12983** [Repooc/ElvUI_ActionBarMasks#7]
Current doesn't work properly with WoW 10.0.7.

When enabled, it causes spell-flyouts in the spell book to not work; the don't "fly out" at all. Not sure if this is just an issues with WoW 10.0.7 or with the newest ElvUI as well.

**Comment by Repooc** [comment]
On line [521](https://github.com/Repooc/ElvUI_ActionBarMasks/blob/main/ElvUI_ActionBarMasks/Core.lua#L521) in Core.lua you can comment out `ABM:SecureHook(AB, 'SetupFlyoutButton')` and you can see your buttons again until either a fix can be found or I just push out a version that doesnt attempt to mask them as well.

**Comment by jdm12983** [comment]
Will give it a try; thanks for the response.

**Comment by jdm12983** [comment]
Just wanted to post back; worked fine; and if anyone else want's to do this: it's actually on line 521 - not 512.

**Comment by Repooc** [comment]
> Just wanted to post back; worked fine; and if anyone else want's to do this: it's actually on line 521 - not 512.

typo'd but linked it correctly lol... was a bit ass backwards lol
